config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
  resources :users, only: [:create]
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :destroy] 

  
  def index
    if logged_in?
      @task = current_user.tasks.build  # form_with 用
      @tasks = current_user.tasks.order(id: :desc)
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    #前の課題版@task = Task.new(task_params)　current_userが必要になるのは当然だが、newとbuildの違いは？
    @task = current_user.tasks.build(task_params)    
    if @task.save
      flash[:success] = 'お仕事が正常に記録されました。お仕事頑張ってください。'
      #前の課題ではredirect_to @taskとしていたが、これで飛ぶtask/indexは結局rootなので、microposts版の記述を使う
      redirect_to root_url
    else
      @tasks = current_user.tasks.order(id: :desc)
      flash.now[:danger] = 'お仕事が正常に記録されませんでした。もう一度記録してください。'
      render :new
      #microposts版ではrender 'toppages/index'となっているが、たぶんnewの方がいい
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'お仕事の情報が正常に修正されました'
      #create同様
      redirect_to root_url
    else
      flash.now[:danger] = 'お仕事の情報が正常に修正されませんでした。やり直してください。'
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = 'このお仕事はお仕事リストから正常に削除されました。お疲れさまでした。'
    #redirect_back(fallback_location: root_path)ではなく、rootに飛ばすことにする
    redirect_to root_url
  end

  private
  
  #共通
  def set_task
    @task = Task.find(params[:id])
  end
  
  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  #edit,destroy用
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">タスクリスト</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'ユーザー登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
　</head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>

  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :content, 'お仕事' %>
  <%= f.text_field :content %>
  
  <%= f.label :status, 'その状況' %>
  <%= f.text_field :status %>

  <%= f.submit '入力・修正' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>お仕事番号 <%= @task.id %> の修正ページ</h1>

<%= render 'form', task: @task %>

<%= link_to 'お仕事一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<% if logged_in? %>
  <h1>やらなければならないお仕事の一覧</h1>
  <ul>
    <% @tasks.each do |task| %>
      <li><%= link_to task.id, task %> : <%= task.content %> : <%= task.status %> </li>
    <% end %>
  </ul>
  <%= link_to '新しいお仕事の追加', new_task_path %>
<% end %>

app/views/tasks/new.html.erb
<h1>やらなければならないお仕事の新規入力ページ</h1>

<%= render 'form', task: @task %>

<%= link_to 'お仕事一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>お仕事番号 <%= @task.id %> の内容、状況の詳細ページ</h1>

<p>お仕事 : <%= @task.content %></p>
<p>その状況 : <%= @task.status %></p>

<%= link_to 'お仕事一覧に戻る', tasks_path %>
<%= link_to 'このお仕事を修正する', edit_task_path(@task) %>
<%= link_to 'このお仕事は気にしなくてよくなったのでお仕事リストから削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザー登録画面</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>

      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'ログイン用メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>